### ISSUE TITLE
Banglish to Bengali is not working the way its expected.

### ISSUE THREAD

**Issue by itsmunim** [porimol/bnbphoneticparser#3]
Try this-

```
banglish_text = 'ami tomay bhalobashi'
print banglish2bengali.parse(banglish_text)
banglish_text = 'mon majhi tor boitha ne re'
print banglish2bengali.parse(banglish_text)
```
This is what gets printed - আমি তমায় ভaলবাশি, মন মাঝি তর বইথa নে রে

**Comment by porimol** [comment]
@dibosh your PR merged :+1:

**Comment by itsmunim** [comment]
@porimol thanks a bunch, mate! But that one doesn't solve this issue, that was just making room for fixing this PR by doing some necessary refactors 😆 Anyhow thanks a bunch 😃More PRs are on its way to fix these issues.
